# eureka information
eureka:
    client:
        service-url:
            defaultZone: http://admin:123456@localhost:8761/eureka
    instance:
        prefer-ip-address: true

# logging
logging:
    level:
        org:
            springframework:
                cloud:
                    gateway: TRACE



# redis information
spring:
    redis:
        database: 0
        host: 192.168.22.65
        port: 6379