# eureka configuration
eureka:
    client:
        service-url:
            defaultZone: http://admin:123456@localhost:8761/eureka
    instance:
        prefer-ip-address: true

# logging configuration
logging:
    level:
        org:
            springframework:
                cloud:
                    gateway: TRACE

spring:
  cloud:
  # gateway configuration
    gateway:
      routes:
        - id: enterprise-data
          uri: lb://enterprise-data
          predicates:
          - Path: /enterprise-data
          filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 3
              key-resolver: "#{@hostAddressKeyResolver}"
        - id: enterprise-portrait
          uri: lb://enterprise-portrait
          predicates:
          - Path: /enterprise-portrait
          filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 3
              key-resolver: "#{@hostAddressKeyResolver}"

  # redis configuration
  redis:
    database: 0
    host: 192.168.22.65
    port: 6379