# eureka configuration
eureka:
    client:
        service-url:
            defaultZone: http://admin:123456@localhost:8761/eureka
    instance:
        prefer-ip-address: true

# logging configuration
logging:
    level:
        org:
            springframework:
                cloud:
                    gateway: debug

spring:
  # redis configuration
  redis:
    host: 192.168.22.65
    port: 6379
  cloud:
  # gateway configuration
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: false
#      routes:
#        - id: enterprise-data
#          uri: lb://enterprise-data
#          predicates:
#            - Path=/enterprise-data/**
#          filters:
#            - StripPrefix=1
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
#                key-resolver: "#{@remoteAddrKeyResolver}"
#        - id: enterprise-portrait
#          uri: lb://enterprise-portrait
#          predicates:
#            - Path=/enterprise-portrait/**
#          filters:
#            - StripPrefix=1
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 3
#                key-resolver: "#{@RemoteAddrKeyResolver}"