# 日志级别配置
logging:
  level:
    org:
      springframework:
        cloud:
          netflix:
            zuul: INFO
# Redis配置
spring:
  redis:
    host: 192.168.22.65
    port: 6379
# 数据源配置
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/bdp-gateway?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      initial-size: 10
      min-idle: 10
      max-active: 50
      test-on-borrow: true


# 限流配置
zuul:
  ratelimit:
    key-prefix: /
    enabled: true
    repository: redis
    behind-proxy: true
    add-response-headers: true
    default-policy-list:
      - limit: 5
        quota: 1000
        refresh-interval: 1
        type:
          - user
          - origin
          - url