# 日志级别配置
logging:
  level:
    org:
      springframework:
        cloud:
          netflix:
            zuul: INFO
# Redis配置
spring:
  redis:
    host: 192.168.22.65
    port: 6379
# 限流配置
zuul:
  ratelimit:
    key-prefix: /
    enabled: true
    repository: redis
    behind-proxy: true
    add-response-headers: true
    default-policy-list:
      - limit: 5
        quota: 1000
        refresh-interval: 1
        type:
          - client
          - origin
          - url