# feign configuration
feign:
    compression:
        request:
            enabled: true
            mime-types: text/html,application/xml,application/json
            min-request-size: 2048
        response:
            enabled: true
    hystrix:
        enabled: false

# logging configuration
logging:
    level:
        com:
            desklamp:
                enterprise:
                    portrait:
                        clients: DEBUG