spring:
  # Security configuration
  security:
    user:
      name: administrator
      password: wql123456
  # Git configuration
  cloud:
    config:
      server:
        git:
          uri: http://192.168.22.65:8001/bdp-desklamp/bdp-config.git
          username: root
          password: mypassword
          clone-on-start: true

# eureka configuration
eureka:
    client:
        service-url:
            defaultZone: http://admin:123456@localhost:8761/eureka
    instance:
        prefer-ip-address: true
# logging configuration
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: INFO




